# Generated by Django 3.2.3 on 2021-06-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Control',
            new_name='Stored',
        ),
    ]
