# Generated by Django 3.2.3 on 2021-06-21 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_control_stored'),
    ]

    operations = [
        migrations.AddField(
            model_name='stored',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
