# Generated by Django 3.2.3 on 2021-06-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_stored_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stored',
            name='stored',
            field=models.CharField(max_length=100),
        ),
    ]
