namespace: web-basics

challenge:
  name: cockroach
  category: web-basics

image:
  repository: ghcr.io/open-education-hub/web-security/web-basics/cockroach
  tag: latest
  pullPolicy: Always

containerPort: 80

service:
  type: NodePort
  port: 80
  nodePort: 30001

healthCheck:
  enabled: true
  path: "/_healthcheck"
  initialDelaySeconds: 5
  periodSeconds: 15
