apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.challenge.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.challenge.name }}
    category: {{ .Values.challenge.category }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ .Values.challenge.name }}
