namespace: web-basics

challenge:
  name: king-kong
  category: web-basics

image:
  repository: ghcr.io/open-education-hub/web-security/web-basics/king-kong
  tag: latest
  pullPolicy: Always

containerPort: 80

service:
  type: NodePort
  port: 80
  nodePort: 30006

healthCheck:
  enabled: true
  path: "/king-kong/"
  initialDelaySeconds: 10
  periodSeconds: 15
