services:
  database:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: sss-web-sql-injection_t0p_s3cr3t_mysql
    environment:
      MYSQL_DATABASE: "secrets"
      MYSQL_USER: "sss"
      MYSQL_PASSWORD: "sss"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - sss-web-sql-injection_t0p_s3cr3t-network
    volumes:
      - "./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 5s
      retries: 10

  sss-web-sql-injection_t0p_s3cr3t-app:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    container_name: sss-web-sql-injection_t0p_s3cr3t
    ports:
      - "12000:80"
    volumes:
      - "../src:/var/www/html"
    networks:
      - sss-web-sql-injection_t0p_s3cr3t-network
    depends_on:
      database:
        condition: service_healthy

networks:
  sss-web-sql-injection_t0p_s3cr3t-network:
