server {
	listen 80;
	listen [::]:80;

	root /var/www/pax.imperia.org/html;
	index index.html index.htm index.nginx-debian.html;

	server_name pax.imperia.org;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;

	root /var/www/pax.imperia.org/html;
	index index.html index.htm index.nginx-debian.html;

	server_name pax.imperia.org;

	ssl on;

	ssl_certificate /etc/ssl/certs/pax.imperia.org.crt;
	ssl_certificate_key /etc/ssl/private/pax.imperia.org.key;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}
}
