apiVersion: v2
name: web-challenge
description: A Helm chart for deploying web security challenges
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - security
  - ctf
  - web
  - challenge
maintainers:
  - name: Gabriel Mocanu
