namespace: web-basics

challenge:
  name: readme
  category: web-basics

image:
  repository: ghcr.io/open-education-hub/web-security/web-basics/readme
  tag: latest
  pullPolicy: Always

containerPort: 80

service:
  type: NodePort
  port: 80
  nodePort: 30013

healthCheck:
  enabled: true
  path: "/readme/"
  initialDelaySeconds: 5
  periodSeconds: 15
