.PHONY: generate clean

generate:
	./generate_support_archive.sh
	make clean

clean:
	rm -rf scripts/serial* scripts/index* scripts/certs scripts/newcerts scripts/private scripts/csr scripts/crl scripts/certs/
