# Generated by Django 3.2.3 on 2021-07-11 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_stored_stored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stored',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 11, 17, 53, 39, 560046)),
        ),
    ]
