# Generated by Django 3.2.3 on 2021-07-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_stored_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stored',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
