namespace: web-basics

challenge:
  name: give-to-get
  category: web-basics

image:
  repository: ghcr.io/open-education-hub/web-security/web-basics/give-to-get
  tag: latest
  pullPolicy: Always

containerPort: 80

service:
  type: NodePort
  port: 80
  nodePort: 30004

healthCheck:
  enabled: true
  path: "/give-to-get/"
  initialDelaySeconds: 10
  periodSeconds: 15
