server {
	listen 80;
	listen [::]:80;

	listen 443 ssl;
	listen [::]:443 ssl;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name __TEMPLATE__;

	ssl on;

	ssl_certificate /etc/ssl/certs/__TEMPLATE__.crt;
	ssl_certificate_key /etc/ssl/private/__TEMPLATE__.key;

	ssl_client_certificate /etc/nginx/client_certs/ca.crt;
	ssl_verify_client optional;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;

		if ($ssl_client_verify != SUCCESS) {
			return 403;
		}
	}
}
