namespace: cookies-and-session-management

challenge:
  name: santa
  category: cookies-and-session-management

image:
  repository: ghcr.io/open-education-hub/web-security/cookies-and-session-management/santa
  tag: latest
  pullPolicy: Always

containerPort: 80

service:
  type: NodePort
  port: 80
  nodePort: 30021

healthCheck:
  enabled: true
  path: "/santa"
  initialDelaySeconds: 5
  periodSeconds: 15
